### ISSUE TITLE
Vuex would throw warnings about modules getting overridden if I call render() in more than one test

### ISSUE THREAD

**Issue by davidchai717** [testing-library/vue-testing-library#158] opened 2020-09-25 18:59 UTC
Oddly this doesn't have if you only have one test that calls render(component, { state: { foo: true }, modules: {...} }). But once I start adding in a second test where I need to render the same component with a Vuex store, it immediately starts throwing these module warnings.

I'd definitely appreciate some assistance here.

**Comment by afontcu** [comment] 2020-10-31 22:55
Hi! Sorry this slipped through the cracks. Do you still experience this issue? 

Could you share a snippet/codesandbox/repo where the issue could be reproduced? That'd help a lot.

I'd suggest making sure you're not sharing the component instance between tests.


Cheers! 👋

**Comment by ITenthusiasm** [comment] 2020-11-24 13:34
@davidchai717 Is the example code you provided (`render(component, { state: { foo: true }, modules: {...} })`) literally what's in your code base right now? If it is, you're missing the `store` property in the object scheme. It would be easier if you wrote something like

```javascript
const store = { state: { foo: true }, modules: {...} };
render(component, { store });
```

But if that isn't your issue then as afontcu said, a code snippet would be really helpful in getting to the bottom of this.

**Comment by afontcu** [comment] 2020-12-15 13:28
Closing as we fixed the issue in Discord :) Turns out lodash' `merge` mutates original source, so the store object was leaking between tests.

**Closed by afontcu** 2020-12-15 13:28 UTC
Labels: bug

**Comment by lukashambsch** [comment] 2021-04-28 20:42
@afontcu What commit fixed this? Has it been released already? I'm seeing the same issue on 5.6.2 right now.

**Comment by afontcu** [comment] 2021-04-29 07:08
The fix was to avoid mutating the original store when using lodash `merge`, and create a new object instead. No fix in VTL was needed 😉

**Comment by lukashambsch** [comment] 2021-04-29 13:47
> The fix was to avoid mutating the original store when using lodash `merge`, and create a new object instead. No fix in VTL was needed 😉

Ahh, I see. Thanks!
